#!/bin/bash
clear
#——————————————————
# CREATED BY @KHALEDAGN
# autoscript-ssh-slowdns TUNNEL
#——————————————————

RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CORTITLE='\033[1;41m'
SCOLOR='\033[0m'
banner='
 ___ _    _____      _____  _  _ ___ 
/ __| |  / _ \ \    / /   \| \| / __|
\__ \ |_| (_) \ \/\/ /| |) | .  \__ \
|___/____\___/ \_/\_/ |___/|_|\_|___/'

echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${CORTITLE}       SSHPLUS CLIENT autoscript-ssh-slowdns       ${SCOLOR}"
echo -e "${CORTITLE}=====================================${SCOLOR}" 
echo -e "${RED}$banner${SCOLOR}"
[[ ! -e dns ]] && {
    yes| termux-setup-storage > /dev/null 2>&1
    unset LD_PRELOAD > /dev/null 2>&1
    cd $HOME
    mv autoscript-ssh-slowdns $PREFIX/bin/autoscript-ssh-slowdns
    chmod +x $PREFIX/bin/autoscript-ssh-slowdns
    [[ $(grep -c 'autoscript-ssh-slowdns' $PREFIX/etc/profile) == '0' ]] && echo 'autoscript-ssh-slowdns' >> $PREFIX/etc/profile
    echo -e "\n${GREEN}DOWNLOADING THE SCRIPT PLEASE WAIT ! ${SCOLOR}"
    curl -O https://raw.githubusercontent.com/Internetvps/autoscript-ssh-slowdns/main/files/dns > /dev/null 2>&1
    echo -e "\n${RED}[${YELLOW}!${RED}] ${YELLOW}SCRIPT DOWNLOADED! THE NEXT TIME\nJUST RUN THE COMMAND ${RED}(${GREEN}autoscript-ssh-slowdns${RED})\n${YELLOW}EVEN IF YOU ARE OFFLINE !${SCOLOR}"
    chmod +x dns
}
[[ ! -e $HOME/credenciais ]] && {
    ns=$1
    [[ -z "$ns" ]] && {
        echo -e "\n${RED}COMMAND INCOMPLETE${SCOLOR}"
        exit 0
    }
    chave=$2
    [[ -z "$chave" ]] && {
        echo -e "\n${RED}COMMAND INCOMPLETE${SCOLOR}"
        exit 0
    }
    echo -e "$ns\n$chave" > $HOME/credenciais
} || {
    perg=$(echo "${SCOLOR}[s/n]: ")
    echo -e "\n${YELLOW}SCRIPT IS ALREADY CONFIGURED WITH A\nSERVER AND IS READY TO CONNECT"
    read -p "$(echo -e "${GREEN}WANT TO CONTINUE WITH THE SAME?${SCOLOR} [s/n]: ")" -e -i s opc
    [[ "$opc" != @(s|sim|S|SIM) ]] && {
        rm $HOME/credenciais dns > /dev/null 2>&1
        rm $PREFIX/bin/autoscript-ssh-slowdns > /dev/null 2>&1
        sed -i '/autoscript-ssh-slowdns/d' $PREFIX/etc/profile > /dev/null 2>&1
        echo -e "\n${RED}SCRIPT REMOVED !${SCOLOR}"
        rm autoscript-ssh-slowdns > /dev/null 2>&1
        exit 0
    } || {
        unset LD_PRELOAD > /dev/null 2>&1
        ns=$(sed -n 1p $HOME/credenciais)
        chave=$(sed -n 2p $HOME/credenciais)
    }
}
dns=$3
[[ -z "$dns" ]] && {
    dns='187.50.250.115'
}
echo -ne "\n${RED}[${YELLOW}!${RED}] ${YELLOW}TO CONTINUE MAKE SURE YOU\nIS ONLY WITH THE ${RED}(${YELLOW}MOBILE DATA${RED})\n${YELLOW}ACTIVATED ${GREEN}ENTER ${YELLOW}TO CONTINUE.. ${SCOLOR}"; read
$HOME/dns -udp ${dns}:53 -pubkey ${chave} ${ns} 127.0.0.1:2222 > /dev/null 2>&1 &
echo -e "\n${RED}[${GREEN}√${RED}]${SCOLOR} - ${GREEN}autoscript-ssh-slowdns INITIATED!${SCOLOR} - ${RED}[${GREEN}√${RED}]\n\n${RED}[${YELLOW}!${RED}] ${YELLOW}NOW CONNECT TO A VPN APP\nOR CLICK ON ${GREEN}ENTER ${RED}TO DISCONNECT ${SCOLOR}"; read
piddns=$(ps x| grep -w 'dns' | grep -v 'grep'| awk -F' ' {'print $1'})
[[ ${piddns} != '' ]] && kill ${piddns} > /dev/null 2>&1
